import Fastify from 'fastify'; import 'dotenv/config'; import { z } from 'zod'; import { migrate, pool, assertConnection } from '../../../packages/database/src/db.js'; import { SUPPORTED_RESOURCES } from '../../../packages/domain/src/models.js';
const app=Fastify({logger:true});
const orgHeader=(req:any)=>String(req.headers['x-organization-id']??'');
app.get('/healthz',async()=>({ok:true,service:'simpro-connector'}));
app.get('/v1/connections',async(req)=>{const org=orgHeader(req); if(!org) return app.httpErrors.badRequest('x-organization-id is required'); const r=await pool.query('select id,name,base_url,company_id,status,created_at,last_checked_at from simpro_connections where organization_id=$1 order by created_at desc',[org]); return r.rows;});
app.post('/v1/connections',async(req,reply)=>{const org=orgHeader(req); const input=z.object({name:z.string().min(1),baseUrl:z.string().url(),companyId:z.string().min(1)}).parse(req.body); const r=await pool.query('insert into simpro_connections(organization_id,name,base_url,company_id) values($1,$2,$3,$4) returning id,name,base_url,company_id,status',[org,input.name,input.baseUrl,input.companyId]); return reply.code(201).send(r.rows[0]);});
app.get('/v1/resources/:connectionId/:resource',async(req:any)=>{const org=orgHeader(req); const {connectionId,resource}=req.params; if(!SUPPORTED_RESOURCES.includes(resource)) return app.httpErrors.badRequest('Unsupported resource'); const c=await assertConnection(org,connectionId); return {connectionId:c.id,resource,items:[],next:'Implement OAuth token resolution and Simpro fetch'};});
app.post('/v1/exports',async(req:any,reply)=>{const org=orgHeader(req); const input=z.object({connectionId:z.string(),resource:z.enum(SUPPORTED_RESOURCES),format:z.enum(['csv','json','xlsx']),filters:z.record(z.unknown()).optional()}).parse(req.body); await assertConnection(org,input.connectionId); const r=await pool.query('insert into export_jobs(organization_id,connection_id,resource,format,filters) values($1,$2,$3,$4,$5) returning id,status,created_at',[org,input.connectionId,input.resource,input.format,input.filters??{}]); return reply.code(202).send(r.rows[0]);});
const port=Number(process.env.PORT??3000); migrate().then(()=>app.listen({port,host:'0.0.0.0'})).catch(e=>{app.log.error(e);process.exit(1)});
